// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_MusteriTakipUygulaması.Models;

#nullable disable

namespace Mvc_MusteriTakipUygulaması.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230329075954_istakipeklendi")]
    partial class istakipeklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc_MusteriTakipUygulaması.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("Varchar(20)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Mvc_MusteriTakipUygulaması.Models.Client", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimYetkilisiAdiSoyadi1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimYetkilisiAdiSoyadi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimYetkilisiAdiSoyadi3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiAdiSoyadi1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiAdiSoyadi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiAdiSoyadi3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiMail1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiMail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImzaYetkilisiMail3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSitesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Mvc_MusteriTakipUygulaması.Models.IsTakip", b =>
                {
                    b.Property<int>("IsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsID"));

                    b.Property<string>("HarcBedeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizmetBedeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsiTakipEdenPersonel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsinTeslimEdilecegiYetkili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToplamFaturaBedeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakIs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IsID");

                    b.ToTable("IsTakips");
                });
#pragma warning restore 612, 618
        }
    }
}
